dist: xenial
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # nightly needs pyflakes 2.1.0, waiting for flake8 update
  #- "nightly"
env:
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.5
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
  - DJANGO=2.0.10 CRYPTOGRAPHY=2.5
  - DJANGO=2.0.10 CRYPTOGRAPHY=2.4.2
  - DJANGO=2.0.10 CRYPTOGRAPHY=2.3.1
  - DJANGO=2.0.10 CRYPTOGRAPHY=2.2.2
  - DJANGO=2.0.10 CRYPTOGRAPHY=2.1.4
  - DJANGO=1.11.18 CRYPTOGRAPHY=2.5
  - DJANGO=1.11.18 CRYPTOGRAPHY=2.4.2
  - DJANGO=1.11.18 CRYPTOGRAPHY=2.3.1
  - DJANGO=1.11.18 CRYPTOGRAPHY=2.2.2
  - DJANGO=1.11.18 CRYPTOGRAPHY=2.1.4
install:
  # Build/test dependencies
 - pip install -U pip setuptools
 - pip install -r requirements/requirements-libs.txt -r requirements-dev.txt
 - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
#before_script:
script:
  - python setup.py code_quality
  - python setup.py test
  - python setup.py install
  - fab init_demo
  - make -C docs html-check

matrix:
    exclude:
        # Django 2.0 no longer supports python2
        # Django 2.1 no longer supports python3.4
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.5
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.5
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
          python: "2.7"
        - env: DJANGO=2.0.10 CRYPTOGRAPHY=2.5
          python: "2.7"
        - env: DJANGO=2.0.10 CRYPTOGRAPHY=2.4.2
          python: "2.7"
        - env: DJANGO=2.0.10 CRYPTOGRAPHY=2.3.1
          python: "2.7"
        - env: DJANGO=2.0.10 CRYPTOGRAPHY=2.2.2
          python: "2.7"
        - env: DJANGO=2.0.10 CRYPTOGRAPHY=2.1.4
          python: "2.7"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.4.2
          python: "3.7"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.3.1
          python: "3.7"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.2.2
          python: "3.7"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.1.4
          python: "3.7"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.4.2
          python: "nightly"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.3.1
          python: "nightly"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.2.2
          python: "nightly"
        - env: DJANGO=1.11.18 CRYPTOGRAPHY=2.1.4
          python: "nightly"
