dist: xenial
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # waiting for the next release of pyflakes, see
  # https://github.com/PyCQA/pyflakes/issues/367
  #- "nightly"
env:
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
  - DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
  - DJANGO=2.0.9 CRYPTOGRAPHY=2.4.2
  - DJANGO=2.0.9 CRYPTOGRAPHY=2.3.1
  - DJANGO=2.0.9 CRYPTOGRAPHY=2.2.2
  - DJANGO=2.0.9 CRYPTOGRAPHY=2.1.4
  - DJANGO=1.11.16 CRYPTOGRAPHY=2.4.2
  - DJANGO=1.11.16 CRYPTOGRAPHY=2.3.1
  - DJANGO=1.11.16 CRYPTOGRAPHY=2.2.2
  - DJANGO=1.11.16 CRYPTOGRAPHY=2.1.4
install:
  # Build/test dependencies
 - pip install -U pip setuptools
 - pip install -r requirements/requirements-libs.txt -r requirements-dev.txt
 - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
#before_script:
script:
  - python setup.py code_quality
  - python setup.py test
  - python setup.py install
  - fab init_demo
  - make -C docs html-check

matrix:
    exclude:
        # Django 2.0 no longer supports python2
        # Django 2.1 no longer supports python3.4
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.4.2
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.3.1
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.2.2
          python: "2.7"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
          python: "3.4"
        - env: DJANGO=2.1.5 CRYPTOGRAPHY=2.1.4
          python: "2.7"
        - env: DJANGO=2.0.9 CRYPTOGRAPHY=2.4.2
          python: "2.7"
        - env: DJANGO=2.0.9 CRYPTOGRAPHY=2.3.1
          python: "2.7"
        - env: DJANGO=2.0.9 CRYPTOGRAPHY=2.2.2
          python: "2.7"
        - env: DJANGO=2.0.9 CRYPTOGRAPHY=2.1.4
          python: "2.7"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.4.2
          python: "3.7"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.3.1
          python: "3.7"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.2.2
          python: "3.7"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.1.4
          python: "3.7"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.4.2
          python: "nightly"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.3.1
          python: "nightly"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.2.2
          python: "nightly"
        - env: DJANGO=1.11.16 CRYPTOGRAPHY=2.1.4
          python: "nightly"

#notifications:
#  irc:
#    channels: "irc.freenode.org#fabric"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: change
#  email: false
